### ISSUE TITLE
Make use of git hooks

### ISSUE THREAD

**Issue by paked** [ncss-2015-group-4/trivia#17]
Using a git hook we could automate the creation of the database, making it generally easier and less to remember for all of us :)

**Comment by auscompgeek** [comment]
I don't think there's a hook for cloning though...

**Comment by auscompgeek** [comment]
If you mean a post-pull hook, that's bad for production systems.

**Comment by paked** [comment]
Good point

**Comment by paked** [comment]
We could have a pre-commit hook for testing though?

**Comment by paked** [comment]
This seems a bit to sophisticated for the moment.
