### ISSUE TITLE
Show questions and answers at the end of a game

### ISSUE THREAD

**Issue by paked** [ncss-2015-group-4/trivia#25]

**Comment by auscompgeek** [comment]
This is something that @sbudiono and I intended. There is a `results.html` template that we could merge into `postgamelobby.html`...

**Comment by paked** [comment]
Seems doable.

**Comment by paked** [comment]
@katharosada finished this off with fcaa461e0a5afcf3e0ee137d31feaba82ce9c411

**Comment by katharosada** [comment]
Ah, sorry I didn't see the issue for this.

**Comment by paked** [comment]
No problemo :)
