### ISSUE TITLE
Login page currently lies to the user

### ISSUE THREAD

**Issue by auscompgeek** [ncss-2015-group-4/trivia#32]
The login page currently says a user can log in using their email instead of their username. This apparently broke in 753e8e03.

Users should be able to log in using either a username or an email as they wish.

Thoughts? /cc @paked @lkw657

**Comment by lkw657** [comment]
I agree with either username or email as they wish

**Comment by paked** [comment]
Too much ambiguity, I am more than happy to re implement this (it appears
I'm the one who took it out)
