### ISSUE TITLE
Allow for specifying listening port at runtime

### ISSUE THREAD

**Issue by paked** [ncss-2015-group-4/trivia#8]
eg. A way to pass in port numbers and a password salt?

**Comment by auscompgeek** [comment]
- salts should always be randomised
- port should ideally be passed in through command line arguments

**Comment by paked** [comment]
Where should salts be stored then, the DB?
+I meant command line arguments

**Comment by auscompgeek** [comment]
Salts should be stored in the database alongside the passhash.

**Comment by auscompgeek** [comment]
See #10 for password salts.

**Comment by paked** [comment]
Implemented with 7293a700bfc9280bf66fdffd4fbd6208f3403332
